---
name: Build and Publish Images

on:
  push:
    branches:
      - redhat-**
      - build-release-branch

jobs:
  build-and-publish:
    name: Publish Quay container image
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: branch name
        run: echo ${GITHUB_REF#refs/heads/}

      - name: format tag from branch
        if: startsWith('redhat-', env.GITHUB_REF)
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo ${BRANCH_NAME/redhat-/}

          # - name: Build and push
          #   id: docker_build
          #   uses: docker/build-push-action@v2
          #   with:
          #     push: true
          #     tags: quay.io/projectquay/quay:3.5
